export const cravingWords = [
  'pizza',
  'tapioca',
  'sushi',
  'carne de sol',
  'hambúrguer',
  'feijoada',
  'yakisoba',
  'açaí',
  'pastel',
  'churrasco',
  'coxinha',
  'lasanha',
  'moqueca',
  'baião de dois',
  'acarajé',
  'escondidinho',
  'buchada',
  'sarapatel',
  'cartola',
  'bolo de rolo',
  'cuscuz',
  'macaxeira',
  'charque',
  'galinha caipira',
  'peixada',
  'caranguejo',
  'camarão',
  'agulhinha frita',
  'caldinho',
  'queijo coalho',
  'arrumadinho',
  'sanduíche',
  'x-tudo',
  'cachorro-quente',
  'espetinho',
  'picanha',
  'costela',
  'fraldinha',
  'cupim',
  'maminha',
  'frango assado',
  'galeto',
  'parmegiana',
  'strogonoff',
  'bife acebolado',
  'prato feito',
  'marmita',
  'self-service',
  'rodízio',
  'temaki',
  'uramaki',
  'sashimi',
  'lámen',
  'guioza',
  'poke',
  'pad thai',
  'curry',
  'dim sum',
  'bibimbap',
  'frango frito',
  'tacos',
  'burrito',
  'nachos',
  'quesadilla',
  'ceviche',
  'paella',
  'risoto',
  'nhoque',
  'espaguete',
  'carbonara',
  'fettuccine',
  'calzone',
  'focaccia',
  'bruschetta',
  'fondue',
  'crepe',
  'waffle',
  'panqueca',
  'omelete',
  'salada',
  'wrap',
  'falafel',
  'shawarma',
  'kebab',
  'esfiha',
  'quibe',
  'kafta',
  'homus',
  'fish and chips',
  'costelinha bbq',
  'asinha',
  'batata frita',
  'mandioca frita',
  'polenta frita',
  'bacalhoada',
  'empada',
  'empadão',
  'torta salgada',
  'sopa',
  'caldo verde',
  'churros',
  'sorvete',
  'petit gâteau',
  'brigadeiro',
  'cocada',
  'pudim',
]
